### ISSUE TITLE
Replying from old issue*

### ISSUE THREAD

**Issue by hoangxuanlam2007** [pdkhanh3011/tftactics0523#1]
# Well... Thanks vì ông đã cho tôi có cơ hội join cái project này. Thực ra thì đối với tôi thì cái idea và project của ông khá là tuyệt, mà cũng bởi vì vừa thích code mà vừa thích chơi dtcl nên tôi mới thử code. Thử làm xong thì tôi thấy có nhiều việc phải làm quá á ông, mà cũng ngại nên mới đi kiếm source làm cho dễ :v

>So... Tôi muốn tgia á nma nếu ông có fb hay gì để có gì liên lạc cho dễ dc k :v, tôi ko phiền lắm đâu với lại ông cx có thể tắt thông báo. Nếu ông chấp nhận cho tui tham gia cái dự án này thì thực ra tôi có vài cái muốn confess ^^

### 1.  Trước tiên thì về xưng hô á, **actually em 2k7, mới vào lớp 10** và đang trong kỳ thi cuối HK2, mà mai là thi xong rồi nên hè e có khá là nhiều thời gian rảnh để có thể thực hiện đam mê làm dev của mình. Em trước giờ toàn tự học code, từ hồi lớp 7 rồi, cuối lớp 8 thì tìm hiểu library framework các thứ, còn hiện tại thì cũng muốn dùng database, rồi oauth các kiểu, lưu data, làm authenticator, backend như SQL... Nên nếu a muốn thì mình có thể đổi **xưng hô** thành `anh với em` thay vì `tôi và ông` 😕 

2. Tiếp theo á, vì thực ra e cũng hiểu project này chỉ là `j4f` (just for fun), mà lại còn là clone [**tftactics**](https://tftactics.gg/). Em cũng có xem qua dtcl.gg của mấy ông 🇻🇳 mình rồi, em thấy lỗi tùm lum lắm :v với lại cái UI nó ko được đẹp, chưa kể nó chưa hoàn thiện ý. Thì em có ý tưởng, là nếu có thể, mình sẽ biến cái project này thực sự thành 1 trang web luôn để ae dtcl việt nam có thể vào check đội hình hot meta, xem tướng, lõi, tộc hệ, tự build đội hình các thứ,... Thì lần trước e forked cái git của anh về, e cũng customized được khá nhiều thứ á ^^ Nếu mà anh đồng ý thì hè này mình triển luôn. Nma em thấy cũng nên đổi UI sang tiếng việt ý anh, database các thứ cũng qua tiếng việt hết để dễ thao tác, chứ có khi ngoài ae mình ra mấy ông khác cũng khó đọc được á.

3. Như em đã nói thì em có dùng code của anh, đây là một vài ảnh về thành phẩm á mặc dù chưa hoàn thiện lắm 😯 , chưa kể em đã lên thẳng cái web của riot, bật `dev mode F12` vô phần `Application` xong tải nguyên cái font của bọn riot về cắm vào web nhìn cho đẹp ý anh mà đẹp thật, hơn cái của tftactics nhiều:

> Cái này là `Home page` nhìn đẹp dko anh =)))
![image](https://github.com/khanh3118/tftactics0523/assets/89345805/9e81b855-c5cd-49eb-98e6-3db2608628c5)
![image](https://github.com/khanh3118/tftactics0523/assets/89345805/e62456ae-28ec-417f-af99-26ce42159f33)
![image](https://github.com/khanh3118/tftactics0523/assets/89345805/f25955d2-899e-4d47-8f9f-907b9096cc86)
![image](https://github.com/khanh3118/tftactics0523/assets/89345805/c7340525-d8e6-4a55-95f1-c47fa80ac0c5)
> Như anh có thể thấy thì có khá là nhiều phần được em thêm vào á :v cũng lấy ý tưởng từ  [**tftactics**](https://tftactics.gg/). 
> Nma chắc chắn khi mình triển khai cái sản phẩm sau khi hoàn thành thì sẽ bỏ cái phần open source kia đi vì mình ko thể cho ngkhac xem á, còn nếu anh muốn thì mình có thể giữ nguyên, phần contact thì để cả 2 ae mình r link vào cái github này. Và sẽ tuyệt vời hơn nếu mình ko để tên web như kia nữa, thay vào đấy là 1 cái tên khác, vdu như em để là `TFTactician` nma mình có thể chọn 1 cái tên tốt hơn, dễ nhớ và gần gũi cho ae VN. Logo thì anh không phải lo vì ngoài code thì em còn rành thiết kế đồ họa với edit dữ lắm, toàn AE, Ps, Ai với Lr thôi^^

4. Cái UI kia em cũng đã việt hóa rồi á :vv
> Còn phần Patch note này em bị lười nên embed thẳng cái post của web dtcl chính thức của riot bằng iframe cho nhanh.
![image](https://github.com/khanh3118/tftactics0523/assets/89345805/dc4380f1-528c-485c-ae68-b177ebf3b1a6)

### Zalo SDT: 0962913298

> À e cũng xin lỗi vì giờ mới rep tại vì e bận ôn thi, mà cái issue kia e tạo a close rồi e ko thấy, nãy mở gmail mới thấy á.
> edited: btw nếu anh muốn thì a có thể check mấy cái `respositories` của em =)))

**Comment by pdkhanh3011** [comment]
add fb anh https://www.facebook.com/profile.php?id=100008397931030
